
# Classes to track
cls_to_track:
  - 1
  - 2
  - 3
  - 6
  - 8

# Detection Parameters
ckpt: null  # Checkpoint for evaluation
conf: 0.12  # Confidence threshold for detection
nms: 0.1  # Non-maximum suppression threshold
tsize: null  # Test image size (optional)
seed: null  # Evaluation seed (optional)

# Tracking Parameters
track_thresh: 0.85  # Detection confidence threshold for tracking
nms_iou_thresh_det: 0.60
lower_bound_det_threshold: 0.5
iou_thresh: 0.2  # IOU threshold for SORT matching
min_hits: 5  # Minimum hits to create track in SORT
inertia: 0.2  # Weight of VDC term in cost matrix - 0.4
deltat: 1  # Time step difference to estimate direction
track_buffer: 20  # Frames for keeping lost tracks
max_exist: 1801
match_thresh: 0.85  # Matching threshold for tracking
min-box-area: 150  # Filter out tiny boxes
gt-type: "_val_half"  # Suffix for ground truth annotation
mot20: false  # Test on MOT20 dataset
public: false  # Use public detection
asso: "giou"  # Similarity function for matching
use_byte: true  # Use Byte in tracking

# KITTI/BDD100K Inference with Public Detections
hp: false  # Use head padding to add missing objects during track initialization (offline)

# Demo Video Settings
demo_type: "image"  # Demo type (image, video, or webcam)
path: "videos/dance_demo.mp4"  # Path to images or video
camid: 0  # Webcam demo camera ID
save_result: true  # Whether to save the inference result of image/video
aspect_ratio_thresh: 1.5  # Threshold for filtering boxes with aspect ratio above this value
min_box_area: 8  # Filter out tiny boxes
device: "gpu"  # Device to run the model (cpu or gpu)

detection_input_folder: "C:/transmetric/AI_system/output/raw_detections/067-00007_Wed_Thur_27hrs_1500/2024_1204_154045_002A/2024_1204_154045_002A_2025_0121_172836_raw_detection/p_detections.parquet"
track_output_dir: "C:/transmetric/AI_system/output"

# INFERENCE CONFIGURATION
camera_index: 0
live: False
debug: False
save_detection: True
detection_files_output_dir: "C:/transmetric/AI_system/output"
detection_videos_output_dir: "C:/transmetric/AI_system/output"
video_list:
  - "C:/transmetric/dev/python/AI_camera/trial/FRCNN+OCS/video/video_traffic_2.mp4"
  - "C:/transmetric/trafficdata/video/goschen/067-00007_Wed_Thur_27hrs_1500/2024_1204_154045_002A.MP4"

pretrained_model: "fasterrcnn_resnet50_fpn"
img_size: 0
show: True
evaluate: True

# Set video_track to true for video inferences and tracking
video_track: True


