camera_index: 0
live: False
debug: False
save_detection: True

detection_files_output_dir: "C:/transmetric/dev/python/AI_camera/trial/FRCNN+OCS/example_det_dir"
detection_videos_output_dir: "C:/transmetric/dev/python/AI_camera/output/videos/v1/goschen"
video_list:
  - "C:/transmetric/trafficdata/video/goschen/067-00006_Mon_Wed_44hrs_2000/2024_1203_065010_023A.MP4"

pretrained_model: "fasterrcnn_resnet50_fpn"
img_size: 0
show: True
evaluate: True

video_track: True
files_track: False
