camera_index: 0
live: False
debug: False
save_detection: True
input_video: "C:/transmetric/trafficdata/video/067-00007_Wed_Thur_27hrs_1500/2024_1204_154045_002A.MP4"
lines_file_path: "./lines_data/2024_0323_120137_100A_line_data_2_3_2.csv"

detection_output_dir: "C:/transmetric/dev/python/AI_camera/output/detections/lincoln_drive"
video_list:
  - "C:/transmetric/trafficdata/video/testcam_lincoln/76_899.615.h264"


pretrained_model: "fasterrcnn_resnet50_fpn"
score_threshold: 0.8
detect_threshold: 0.8
max_frame_track: 30
byte_track_embedder: "mobilenet"
img_size: 0
show: True
cls_to_track:
  - 1
  - 2
  - 3
  - 6
  - 8
evaluate: True
infer_samples: True
